### ISSUE TITLE
Module not updating 

### ISSUE THREAD

**Issue by Baxerino** [teppos/MMM-SL#3]
The module doesnt updating until i manually restart the magic mirror with pm2 restart mm,

here's my config for MMM-SL

{
module: ‘MMM-SL’,
position: “top_left”,	
config: {
realtimeappid: ‘my_api_key’,
timewindow: ‘30’,
updateNotification: “UPDATE_SL”,
siteids: [
{
id: “XXXX”
},
{
id: “XXXX”
},
]	
},

**Comment by petersbk** [comment]
Try with 'single' quotation marks instead; i.e. 'UPDATE_SL' instead of "UPDATE_SL"... (and for position: "top_left",) - it worked for me...

**Comment by teppos** [comment]
The module doesn't update the values by itself.
See https://github.com/teppos/MMM-SL#events for information on how to schedule update
